services:
  web:
    # Forward port 5173 from the host to the container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Tell Vite to use the host's dev server
      - VITE_HOST_URL=http://host.docker.internal:5173